/*
 * generated by Xtext 2.32.0
 */
package co7217.week18.entity.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class EntityDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class PluginElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co7217.week18.entity.EntityDsl.Plugin");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPluginKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameSTRINGTerminalRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		private final Keyword cVersionKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cEqualsSignKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cVersionAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cVersionSTRINGTerminalRuleCall_7_0 = (RuleCall)cVersionAssignment_7.eContents().get(0);
		private final Keyword cDescriptionKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cEqualsSignKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cDescriptionAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_10_0 = (RuleCall)cDescriptionAssignment_10.eContents().get(0);
		private final Keyword cAuthorKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cEqualsSignKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cAuthorAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cAuthorSTRINGTerminalRuleCall_13_0 = (RuleCall)cAuthorAssignment_13.eContents().get(0);
		private final Keyword cLicenseKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cEqualsSignKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Assignment cLicenseAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final RuleCall cLicenseSTRINGTerminalRuleCall_16_0 = (RuleCall)cLicenseAssignment_16.eContents().get(0);
		private final Keyword cPrefixKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Keyword cEqualsSignKeyword_18 = (Keyword)cGroup.eContents().get(18);
		private final Assignment cPrefixAssignment_19 = (Assignment)cGroup.eContents().get(19);
		private final RuleCall cPrefixSTRINGTerminalRuleCall_19_0 = (RuleCall)cPrefixAssignment_19.eContents().get(0);
		private final Keyword cTextDomainKeyword_20 = (Keyword)cGroup.eContents().get(20);
		private final Keyword cEqualsSignKeyword_21 = (Keyword)cGroup.eContents().get(21);
		private final Assignment cTextDomainAssignment_22 = (Assignment)cGroup.eContents().get(22);
		private final RuleCall cTextDomainSTRINGTerminalRuleCall_22_0 = (RuleCall)cTextDomainAssignment_22.eContents().get(0);
		private final Keyword cActivateKeyword_23 = (Keyword)cGroup.eContents().get(23);
		private final Keyword cEqualsSignKeyword_24 = (Keyword)cGroup.eContents().get(24);
		private final Assignment cActivateAssignment_25 = (Assignment)cGroup.eContents().get(25);
		private final RuleCall cActivateSTRINGTerminalRuleCall_25_0 = (RuleCall)cActivateAssignment_25.eContents().get(0);
		private final Keyword cDeactivateKeyword_26 = (Keyword)cGroup.eContents().get(26);
		private final Keyword cEqualsSignKeyword_27 = (Keyword)cGroup.eContents().get(27);
		private final Assignment cDeactivateAssignment_28 = (Assignment)cGroup.eContents().get(28);
		private final RuleCall cDeactivateSTRINGTerminalRuleCall_28_0 = (RuleCall)cDeactivateAssignment_28.eContents().get(0);
		private final Assignment cWidgetsAssignment_29 = (Assignment)cGroup.eContents().get(29);
		private final RuleCall cWidgetsWidgetParserRuleCall_29_0 = (RuleCall)cWidgetsAssignment_29.eContents().get(0);
		private final Assignment cShortcodesAssignment_30 = (Assignment)cGroup.eContents().get(30);
		private final RuleCall cShortcodesShortcodeParserRuleCall_30_0 = (RuleCall)cShortcodesAssignment_30.eContents().get(0);
		private final Assignment cCustomPostTypesAssignment_31 = (Assignment)cGroup.eContents().get(31);
		private final RuleCall cCustomPostTypesCustomPostTypeParserRuleCall_31_0 = (RuleCall)cCustomPostTypesAssignment_31.eContents().get(0);
		private final Assignment cSettingsAssignment_32 = (Assignment)cGroup.eContents().get(32);
		private final RuleCall cSettingsSettingParserRuleCall_32_0 = (RuleCall)cSettingsAssignment_32.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_33 = (Keyword)cGroup.eContents().get(33);
		
		//Plugin:
		//    'Plugin' '{'
		//        'name' '=' name=STRING
		//        'version' '=' version=STRING
		//        'description' '=' description=STRING?
		//        'author' '=' author=STRING?
		//        'license' '=' license=STRING?
		//        'prefix' '=' prefix=STRING?
		//        'textDomain' '=' textDomain=STRING?
		//        'activate' '=' activate=STRING?
		//        'deactivate' '=' deactivate=STRING?
		//        (widgets+=Widget)*
		//        (shortcodes+=Shortcode)*
		//        (customPostTypes+=CustomPostType)*
		//        (settings+=Setting)*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Plugin' '{'
		//    'name' '=' name=STRING
		//    'version' '=' version=STRING
		//    'description' '=' description=STRING?
		//    'author' '=' author=STRING?
		//    'license' '=' license=STRING?
		//    'prefix' '=' prefix=STRING?
		//    'textDomain' '=' textDomain=STRING?
		//    'activate' '=' activate=STRING?
		//    'deactivate' '=' deactivate=STRING?
		//    (widgets+=Widget)*
		//    (shortcodes+=Shortcode)*
		//    (customPostTypes+=CustomPostType)*
		//    (settings+=Setting)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Plugin'
		public Keyword getPluginKeyword_0() { return cPluginKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'name'
		public Keyword getNameKeyword_2() { return cNameKeyword_2; }
		
		//'='
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }
		
		//name=STRING
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_4_0() { return cNameSTRINGTerminalRuleCall_4_0; }
		
		//'version'
		public Keyword getVersionKeyword_5() { return cVersionKeyword_5; }
		
		//'='
		public Keyword getEqualsSignKeyword_6() { return cEqualsSignKeyword_6; }
		
		//version=STRING
		public Assignment getVersionAssignment_7() { return cVersionAssignment_7; }
		
		//STRING
		public RuleCall getVersionSTRINGTerminalRuleCall_7_0() { return cVersionSTRINGTerminalRuleCall_7_0; }
		
		//'description'
		public Keyword getDescriptionKeyword_8() { return cDescriptionKeyword_8; }
		
		//'='
		public Keyword getEqualsSignKeyword_9() { return cEqualsSignKeyword_9; }
		
		//description=STRING?
		public Assignment getDescriptionAssignment_10() { return cDescriptionAssignment_10; }
		
		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_10_0() { return cDescriptionSTRINGTerminalRuleCall_10_0; }
		
		//'author'
		public Keyword getAuthorKeyword_11() { return cAuthorKeyword_11; }
		
		//'='
		public Keyword getEqualsSignKeyword_12() { return cEqualsSignKeyword_12; }
		
		//author=STRING?
		public Assignment getAuthorAssignment_13() { return cAuthorAssignment_13; }
		
		//STRING
		public RuleCall getAuthorSTRINGTerminalRuleCall_13_0() { return cAuthorSTRINGTerminalRuleCall_13_0; }
		
		//'license'
		public Keyword getLicenseKeyword_14() { return cLicenseKeyword_14; }
		
		//'='
		public Keyword getEqualsSignKeyword_15() { return cEqualsSignKeyword_15; }
		
		//license=STRING?
		public Assignment getLicenseAssignment_16() { return cLicenseAssignment_16; }
		
		//STRING
		public RuleCall getLicenseSTRINGTerminalRuleCall_16_0() { return cLicenseSTRINGTerminalRuleCall_16_0; }
		
		//'prefix'
		public Keyword getPrefixKeyword_17() { return cPrefixKeyword_17; }
		
		//'='
		public Keyword getEqualsSignKeyword_18() { return cEqualsSignKeyword_18; }
		
		//prefix=STRING?
		public Assignment getPrefixAssignment_19() { return cPrefixAssignment_19; }
		
		//STRING
		public RuleCall getPrefixSTRINGTerminalRuleCall_19_0() { return cPrefixSTRINGTerminalRuleCall_19_0; }
		
		//'textDomain'
		public Keyword getTextDomainKeyword_20() { return cTextDomainKeyword_20; }
		
		//'='
		public Keyword getEqualsSignKeyword_21() { return cEqualsSignKeyword_21; }
		
		//textDomain=STRING?
		public Assignment getTextDomainAssignment_22() { return cTextDomainAssignment_22; }
		
		//STRING
		public RuleCall getTextDomainSTRINGTerminalRuleCall_22_0() { return cTextDomainSTRINGTerminalRuleCall_22_0; }
		
		//'activate'
		public Keyword getActivateKeyword_23() { return cActivateKeyword_23; }
		
		//'='
		public Keyword getEqualsSignKeyword_24() { return cEqualsSignKeyword_24; }
		
		//activate=STRING?
		public Assignment getActivateAssignment_25() { return cActivateAssignment_25; }
		
		//STRING
		public RuleCall getActivateSTRINGTerminalRuleCall_25_0() { return cActivateSTRINGTerminalRuleCall_25_0; }
		
		//'deactivate'
		public Keyword getDeactivateKeyword_26() { return cDeactivateKeyword_26; }
		
		//'='
		public Keyword getEqualsSignKeyword_27() { return cEqualsSignKeyword_27; }
		
		//deactivate=STRING?
		public Assignment getDeactivateAssignment_28() { return cDeactivateAssignment_28; }
		
		//STRING
		public RuleCall getDeactivateSTRINGTerminalRuleCall_28_0() { return cDeactivateSTRINGTerminalRuleCall_28_0; }
		
		//(widgets+=Widget)*
		public Assignment getWidgetsAssignment_29() { return cWidgetsAssignment_29; }
		
		//Widget
		public RuleCall getWidgetsWidgetParserRuleCall_29_0() { return cWidgetsWidgetParserRuleCall_29_0; }
		
		//(shortcodes+=Shortcode)*
		public Assignment getShortcodesAssignment_30() { return cShortcodesAssignment_30; }
		
		//Shortcode
		public RuleCall getShortcodesShortcodeParserRuleCall_30_0() { return cShortcodesShortcodeParserRuleCall_30_0; }
		
		//(customPostTypes+=CustomPostType)*
		public Assignment getCustomPostTypesAssignment_31() { return cCustomPostTypesAssignment_31; }
		
		//CustomPostType
		public RuleCall getCustomPostTypesCustomPostTypeParserRuleCall_31_0() { return cCustomPostTypesCustomPostTypeParserRuleCall_31_0; }
		
		//(settings+=Setting)*
		public Assignment getSettingsAssignment_32() { return cSettingsAssignment_32; }
		
		//Setting
		public RuleCall getSettingsSettingParserRuleCall_32_0() { return cSettingsSettingParserRuleCall_32_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_33() { return cRightCurlyBracketKeyword_33; }
	}
	public class WidgetElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co7217.week18.entity.EntityDsl.Widget");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWidgetKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cWidgetNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cWidgetNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cWidgetNameSTRINGTerminalRuleCall_4_0 = (RuleCall)cWidgetNameAssignment_4.eContents().get(0);
		private final Keyword cWidgetDescriptionKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cEqualsSignKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cWidgetDescriptionAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cWidgetDescriptionSTRINGTerminalRuleCall_7_0 = (RuleCall)cWidgetDescriptionAssignment_7.eContents().get(0);
		private final Assignment cSettingsAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cSettingsSettingParserRuleCall_8_0 = (RuleCall)cSettingsAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Widget:
		//    'Widget' '{'
		//        'widgetName' '=' widgetName=STRING
		//        'widgetDescription' '=' widgetDescription=STRING
		//        (settings+=Setting)*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Widget' '{'
		//    'widgetName' '=' widgetName=STRING
		//    'widgetDescription' '=' widgetDescription=STRING
		//    (settings+=Setting)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Widget'
		public Keyword getWidgetKeyword_0() { return cWidgetKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'widgetName'
		public Keyword getWidgetNameKeyword_2() { return cWidgetNameKeyword_2; }
		
		//'='
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }
		
		//widgetName=STRING
		public Assignment getWidgetNameAssignment_4() { return cWidgetNameAssignment_4; }
		
		//STRING
		public RuleCall getWidgetNameSTRINGTerminalRuleCall_4_0() { return cWidgetNameSTRINGTerminalRuleCall_4_0; }
		
		//'widgetDescription'
		public Keyword getWidgetDescriptionKeyword_5() { return cWidgetDescriptionKeyword_5; }
		
		//'='
		public Keyword getEqualsSignKeyword_6() { return cEqualsSignKeyword_6; }
		
		//widgetDescription=STRING
		public Assignment getWidgetDescriptionAssignment_7() { return cWidgetDescriptionAssignment_7; }
		
		//STRING
		public RuleCall getWidgetDescriptionSTRINGTerminalRuleCall_7_0() { return cWidgetDescriptionSTRINGTerminalRuleCall_7_0; }
		
		//(settings+=Setting)*
		public Assignment getSettingsAssignment_8() { return cSettingsAssignment_8; }
		
		//Setting
		public RuleCall getSettingsSettingParserRuleCall_8_0() { return cSettingsSettingParserRuleCall_8_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class SettingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co7217.week18.entity.EntityDsl.Setting");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSettingKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cSettingNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cSettingNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cSettingNameSTRINGTerminalRuleCall_4_0 = (RuleCall)cSettingNameAssignment_4.eContents().get(0);
		private final Keyword cSettingTypeKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cEqualsSignKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cSettingTypeAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cSettingTypeSTRINGTerminalRuleCall_7_0 = (RuleCall)cSettingTypeAssignment_7.eContents().get(0);
		private final Keyword cDefaultValueKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cEqualsSignKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cDefaultValueAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cDefaultValueSTRINGTerminalRuleCall_10_0 = (RuleCall)cDefaultValueAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Setting:
		//    'Setting' '{'
		//        'settingName' '=' settingName=STRING
		//        'settingType' '=' settingType=STRING
		//        'defaultValue' '=' defaultValue=STRING?
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Setting' '{'
		//    'settingName' '=' settingName=STRING
		//    'settingType' '=' settingType=STRING
		//    'defaultValue' '=' defaultValue=STRING?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Setting'
		public Keyword getSettingKeyword_0() { return cSettingKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'settingName'
		public Keyword getSettingNameKeyword_2() { return cSettingNameKeyword_2; }
		
		//'='
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }
		
		//settingName=STRING
		public Assignment getSettingNameAssignment_4() { return cSettingNameAssignment_4; }
		
		//STRING
		public RuleCall getSettingNameSTRINGTerminalRuleCall_4_0() { return cSettingNameSTRINGTerminalRuleCall_4_0; }
		
		//'settingType'
		public Keyword getSettingTypeKeyword_5() { return cSettingTypeKeyword_5; }
		
		//'='
		public Keyword getEqualsSignKeyword_6() { return cEqualsSignKeyword_6; }
		
		//settingType=STRING
		public Assignment getSettingTypeAssignment_7() { return cSettingTypeAssignment_7; }
		
		//STRING
		public RuleCall getSettingTypeSTRINGTerminalRuleCall_7_0() { return cSettingTypeSTRINGTerminalRuleCall_7_0; }
		
		//'defaultValue'
		public Keyword getDefaultValueKeyword_8() { return cDefaultValueKeyword_8; }
		
		//'='
		public Keyword getEqualsSignKeyword_9() { return cEqualsSignKeyword_9; }
		
		//defaultValue=STRING?
		public Assignment getDefaultValueAssignment_10() { return cDefaultValueAssignment_10; }
		
		//STRING
		public RuleCall getDefaultValueSTRINGTerminalRuleCall_10_0() { return cDefaultValueSTRINGTerminalRuleCall_10_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class ShortcodeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co7217.week18.entity.EntityDsl.Shortcode");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cShortcodeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cShortcodeNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cShortcodeNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cShortcodeNameSTRINGTerminalRuleCall_4_0 = (RuleCall)cShortcodeNameAssignment_4.eContents().get(0);
		private final Keyword cAddShortcodeKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cExecuteShortcodeKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cHooksAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cHooksHookParserRuleCall_7_0 = (RuleCall)cHooksAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Shortcode:
		//    'Shortcode' '{'
		//        'shortcodeName' '=' shortcodeName=STRING
		//        'addShortcode()'
		//        'executeShortcode()'
		//        (hooks+=Hook)*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Shortcode' '{'
		//    'shortcodeName' '=' shortcodeName=STRING
		//    'addShortcode()'
		//    'executeShortcode()'
		//    (hooks+=Hook)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Shortcode'
		public Keyword getShortcodeKeyword_0() { return cShortcodeKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'shortcodeName'
		public Keyword getShortcodeNameKeyword_2() { return cShortcodeNameKeyword_2; }
		
		//'='
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }
		
		//shortcodeName=STRING
		public Assignment getShortcodeNameAssignment_4() { return cShortcodeNameAssignment_4; }
		
		//STRING
		public RuleCall getShortcodeNameSTRINGTerminalRuleCall_4_0() { return cShortcodeNameSTRINGTerminalRuleCall_4_0; }
		
		//'addShortcode()'
		public Keyword getAddShortcodeKeyword_5() { return cAddShortcodeKeyword_5; }
		
		//'executeShortcode()'
		public Keyword getExecuteShortcodeKeyword_6() { return cExecuteShortcodeKeyword_6; }
		
		//(hooks+=Hook)*
		public Assignment getHooksAssignment_7() { return cHooksAssignment_7; }
		
		//Hook
		public RuleCall getHooksHookParserRuleCall_7_0() { return cHooksHookParserRuleCall_7_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class CustomPostTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co7217.week18.entity.EntityDsl.CustomPostType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCustomPostTypeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPostTypeNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPostTypeNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPostTypeNameSTRINGTerminalRuleCall_4_0 = (RuleCall)cPostTypeNameAssignment_4.eContents().get(0);
		private final Keyword cSupportsKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cEqualsSignKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cSupportsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cSupportsSTRINGTerminalRuleCall_7_0 = (RuleCall)cSupportsAssignment_7.eContents().get(0);
		private final Keyword cTaxonomiesKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cEqualsSignKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cTaxonomiesAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cTaxonomiesSTRINGTerminalRuleCall_10_0 = (RuleCall)cTaxonomiesAssignment_10.eContents().get(0);
		private final Keyword cRegisterPostTypeKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cConfigurePostTypeKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cHooksAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cHooksHookParserRuleCall_13_0 = (RuleCall)cHooksAssignment_13.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//CustomPostType:
		//    'CustomPostType' '{'
		//        'postTypeName' '=' postTypeName=STRING
		//        'supports' '=' supports=STRING?
		//        'taxonomies' '=' taxonomies=STRING?
		//        'registerPostType()'
		//        'configurePostType()'
		//        (hooks+=Hook)*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'CustomPostType' '{'
		//    'postTypeName' '=' postTypeName=STRING
		//    'supports' '=' supports=STRING?
		//    'taxonomies' '=' taxonomies=STRING?
		//    'registerPostType()'
		//    'configurePostType()'
		//    (hooks+=Hook)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'CustomPostType'
		public Keyword getCustomPostTypeKeyword_0() { return cCustomPostTypeKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'postTypeName'
		public Keyword getPostTypeNameKeyword_2() { return cPostTypeNameKeyword_2; }
		
		//'='
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }
		
		//postTypeName=STRING
		public Assignment getPostTypeNameAssignment_4() { return cPostTypeNameAssignment_4; }
		
		//STRING
		public RuleCall getPostTypeNameSTRINGTerminalRuleCall_4_0() { return cPostTypeNameSTRINGTerminalRuleCall_4_0; }
		
		//'supports'
		public Keyword getSupportsKeyword_5() { return cSupportsKeyword_5; }
		
		//'='
		public Keyword getEqualsSignKeyword_6() { return cEqualsSignKeyword_6; }
		
		//supports=STRING?
		public Assignment getSupportsAssignment_7() { return cSupportsAssignment_7; }
		
		//STRING
		public RuleCall getSupportsSTRINGTerminalRuleCall_7_0() { return cSupportsSTRINGTerminalRuleCall_7_0; }
		
		//'taxonomies'
		public Keyword getTaxonomiesKeyword_8() { return cTaxonomiesKeyword_8; }
		
		//'='
		public Keyword getEqualsSignKeyword_9() { return cEqualsSignKeyword_9; }
		
		//taxonomies=STRING?
		public Assignment getTaxonomiesAssignment_10() { return cTaxonomiesAssignment_10; }
		
		//STRING
		public RuleCall getTaxonomiesSTRINGTerminalRuleCall_10_0() { return cTaxonomiesSTRINGTerminalRuleCall_10_0; }
		
		//'registerPostType()'
		public Keyword getRegisterPostTypeKeyword_11() { return cRegisterPostTypeKeyword_11; }
		
		//'configurePostType()'
		public Keyword getConfigurePostTypeKeyword_12() { return cConfigurePostTypeKeyword_12; }
		
		//(hooks+=Hook)*
		public Assignment getHooksAssignment_13() { return cHooksAssignment_13; }
		
		//Hook
		public RuleCall getHooksHookParserRuleCall_13_0() { return cHooksHookParserRuleCall_13_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}
	public class HookElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co7217.week18.entity.EntityDsl.Hook");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHookKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cHookNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cHookNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cHookNameSTRINGTerminalRuleCall_4_0 = (RuleCall)cHookNameAssignment_4.eContents().get(0);
		private final Keyword cCallbackFunctionKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cEqualsSignKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cCallbackFunctionAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cCallbackFunctionSTRINGTerminalRuleCall_7_0 = (RuleCall)cCallbackFunctionAssignment_7.eContents().get(0);
		private final Keyword cAddActionKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cAddFilterKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Hook:
		//    'Hook' '{'
		//        'hookName' '=' hookName=STRING
		//        'callbackFunction' '=' callbackFunction=STRING
		//        'addAction()'
		//        'addFilter()'
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Hook' '{'
		//    'hookName' '=' hookName=STRING
		//    'callbackFunction' '=' callbackFunction=STRING
		//    'addAction()'
		//    'addFilter()'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Hook'
		public Keyword getHookKeyword_0() { return cHookKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'hookName'
		public Keyword getHookNameKeyword_2() { return cHookNameKeyword_2; }
		
		//'='
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }
		
		//hookName=STRING
		public Assignment getHookNameAssignment_4() { return cHookNameAssignment_4; }
		
		//STRING
		public RuleCall getHookNameSTRINGTerminalRuleCall_4_0() { return cHookNameSTRINGTerminalRuleCall_4_0; }
		
		//'callbackFunction'
		public Keyword getCallbackFunctionKeyword_5() { return cCallbackFunctionKeyword_5; }
		
		//'='
		public Keyword getEqualsSignKeyword_6() { return cEqualsSignKeyword_6; }
		
		//callbackFunction=STRING
		public Assignment getCallbackFunctionAssignment_7() { return cCallbackFunctionAssignment_7; }
		
		//STRING
		public RuleCall getCallbackFunctionSTRINGTerminalRuleCall_7_0() { return cCallbackFunctionSTRINGTerminalRuleCall_7_0; }
		
		//'addAction()'
		public Keyword getAddActionKeyword_8() { return cAddActionKeyword_8; }
		
		//'addFilter()'
		public Keyword getAddFilterKeyword_9() { return cAddFilterKeyword_9; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	
	
	private final PluginElements pPlugin;
	private final WidgetElements pWidget;
	private final SettingElements pSetting;
	private final ShortcodeElements pShortcode;
	private final CustomPostTypeElements pCustomPostType;
	private final HookElements pHook;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public EntityDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pPlugin = new PluginElements();
		this.pWidget = new WidgetElements();
		this.pSetting = new SettingElements();
		this.pShortcode = new ShortcodeElements();
		this.pCustomPostType = new CustomPostTypeElements();
		this.pHook = new HookElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("co7217.week18.entity.EntityDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Plugin:
	//    'Plugin' '{'
	//        'name' '=' name=STRING
	//        'version' '=' version=STRING
	//        'description' '=' description=STRING?
	//        'author' '=' author=STRING?
	//        'license' '=' license=STRING?
	//        'prefix' '=' prefix=STRING?
	//        'textDomain' '=' textDomain=STRING?
	//        'activate' '=' activate=STRING?
	//        'deactivate' '=' deactivate=STRING?
	//        (widgets+=Widget)*
	//        (shortcodes+=Shortcode)*
	//        (customPostTypes+=CustomPostType)*
	//        (settings+=Setting)*
	//    '}'
	//;
	public PluginElements getPluginAccess() {
		return pPlugin;
	}
	
	public ParserRule getPluginRule() {
		return getPluginAccess().getRule();
	}
	
	//Widget:
	//    'Widget' '{'
	//        'widgetName' '=' widgetName=STRING
	//        'widgetDescription' '=' widgetDescription=STRING
	//        (settings+=Setting)*
	//    '}'
	//;
	public WidgetElements getWidgetAccess() {
		return pWidget;
	}
	
	public ParserRule getWidgetRule() {
		return getWidgetAccess().getRule();
	}
	
	//Setting:
	//    'Setting' '{'
	//        'settingName' '=' settingName=STRING
	//        'settingType' '=' settingType=STRING
	//        'defaultValue' '=' defaultValue=STRING?
	//    '}'
	//;
	public SettingElements getSettingAccess() {
		return pSetting;
	}
	
	public ParserRule getSettingRule() {
		return getSettingAccess().getRule();
	}
	
	//Shortcode:
	//    'Shortcode' '{'
	//        'shortcodeName' '=' shortcodeName=STRING
	//        'addShortcode()'
	//        'executeShortcode()'
	//        (hooks+=Hook)*
	//    '}'
	//;
	public ShortcodeElements getShortcodeAccess() {
		return pShortcode;
	}
	
	public ParserRule getShortcodeRule() {
		return getShortcodeAccess().getRule();
	}
	
	//CustomPostType:
	//    'CustomPostType' '{'
	//        'postTypeName' '=' postTypeName=STRING
	//        'supports' '=' supports=STRING?
	//        'taxonomies' '=' taxonomies=STRING?
	//        'registerPostType()'
	//        'configurePostType()'
	//        (hooks+=Hook)*
	//    '}'
	//;
	public CustomPostTypeElements getCustomPostTypeAccess() {
		return pCustomPostType;
	}
	
	public ParserRule getCustomPostTypeRule() {
		return getCustomPostTypeAccess().getRule();
	}
	
	//Hook:
	//    'Hook' '{'
	//        'hookName' '=' hookName=STRING
	//        'callbackFunction' '=' callbackFunction=STRING
	//        'addAction()'
	//        'addFilter()'
	//    '}'
	//;
	public HookElements getHookAccess() {
		return pHook;
	}
	
	public ParserRule getHookRule() {
		return getHookAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
