/*
 * generated by Xtext 2.32.0
 */
package co7217.week18.entity.ide.contentassist.antlr;

import co7217.week18.entity.ide.contentassist.antlr.internal.InternalEntityDslParser;
import co7217.week18.entity.services.EntityDslGrammarAccess;
import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class EntityDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(EntityDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, EntityDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getHookTypeAccess().getAlternatives(), "rule__HookType__Alternatives");
			builder.put(grammarAccess.getPluginAccess().getGroup(), "rule__Plugin__Group__0");
			builder.put(grammarAccess.getWidgetAccess().getGroup(), "rule__Widget__Group__0");
			builder.put(grammarAccess.getShortcodeAccess().getGroup(), "rule__Shortcode__Group__0");
			builder.put(grammarAccess.getCustomPostTypeAccess().getGroup(), "rule__CustomPostType__Group__0");
			builder.put(grammarAccess.getSettingAccess().getGroup(), "rule__Setting__Group__0");
			builder.put(grammarAccess.getHookAccess().getGroup(), "rule__Hook__Group__0");
			builder.put(grammarAccess.getPluginAccess().getNameAssignment_4(), "rule__Plugin__NameAssignment_4");
			builder.put(grammarAccess.getPluginAccess().getVersionAssignment_7(), "rule__Plugin__VersionAssignment_7");
			builder.put(grammarAccess.getPluginAccess().getDescriptionAssignment_10(), "rule__Plugin__DescriptionAssignment_10");
			builder.put(grammarAccess.getPluginAccess().getAuthorAssignment_13(), "rule__Plugin__AuthorAssignment_13");
			builder.put(grammarAccess.getPluginAccess().getLicenseAssignment_16(), "rule__Plugin__LicenseAssignment_16");
			builder.put(grammarAccess.getPluginAccess().getPrefixAssignment_19(), "rule__Plugin__PrefixAssignment_19");
			builder.put(grammarAccess.getPluginAccess().getTextDomainAssignment_22(), "rule__Plugin__TextDomainAssignment_22");
			builder.put(grammarAccess.getPluginAccess().getActivateAssignment_25(), "rule__Plugin__ActivateAssignment_25");
			builder.put(grammarAccess.getPluginAccess().getDeactivateAssignment_28(), "rule__Plugin__DeactivateAssignment_28");
			builder.put(grammarAccess.getPluginAccess().getUninstallAssignment_31(), "rule__Plugin__UninstallAssignment_31");
			builder.put(grammarAccess.getPluginAccess().getWidgetsAssignment_32(), "rule__Plugin__WidgetsAssignment_32");
			builder.put(grammarAccess.getPluginAccess().getShortcodesAssignment_33(), "rule__Plugin__ShortcodesAssignment_33");
			builder.put(grammarAccess.getPluginAccess().getCustomPostTypesAssignment_34(), "rule__Plugin__CustomPostTypesAssignment_34");
			builder.put(grammarAccess.getPluginAccess().getSettingsAssignment_35(), "rule__Plugin__SettingsAssignment_35");
			builder.put(grammarAccess.getPluginAccess().getHooksAssignment_36(), "rule__Plugin__HooksAssignment_36");
			builder.put(grammarAccess.getWidgetAccess().getWidgetNameAssignment_4(), "rule__Widget__WidgetNameAssignment_4");
			builder.put(grammarAccess.getWidgetAccess().getWidgetDescriptionAssignment_7(), "rule__Widget__WidgetDescriptionAssignment_7");
			builder.put(grammarAccess.getWidgetAccess().getSettingsAssignment_8(), "rule__Widget__SettingsAssignment_8");
			builder.put(grammarAccess.getShortcodeAccess().getShortcodeNameAssignment_4(), "rule__Shortcode__ShortcodeNameAssignment_4");
			builder.put(grammarAccess.getShortcodeAccess().getSettingsAssignment_5(), "rule__Shortcode__SettingsAssignment_5");
			builder.put(grammarAccess.getCustomPostTypeAccess().getPostTypeNameAssignment_4(), "rule__CustomPostType__PostTypeNameAssignment_4");
			builder.put(grammarAccess.getCustomPostTypeAccess().getSupportsAssignment_7(), "rule__CustomPostType__SupportsAssignment_7");
			builder.put(grammarAccess.getCustomPostTypeAccess().getTaxonomiesAssignment_10(), "rule__CustomPostType__TaxonomiesAssignment_10");
			builder.put(grammarAccess.getSettingAccess().getSettingNameAssignment_4(), "rule__Setting__SettingNameAssignment_4");
			builder.put(grammarAccess.getSettingAccess().getSettingTypeAssignment_7(), "rule__Setting__SettingTypeAssignment_7");
			builder.put(grammarAccess.getSettingAccess().getDefaultValueAssignment_10(), "rule__Setting__DefaultValueAssignment_10");
			builder.put(grammarAccess.getHookAccess().getHookTypeAssignment_4(), "rule__Hook__HookTypeAssignment_4");
			builder.put(grammarAccess.getHookAccess().getHookNameAssignment_7(), "rule__Hook__HookNameAssignment_7");
			builder.put(grammarAccess.getHookAccess().getCallbackAssignment_10(), "rule__Hook__CallbackAssignment_10");
			builder.put(grammarAccess.getHookAccess().getPriorityAssignment_13(), "rule__Hook__PriorityAssignment_13");
			builder.put(grammarAccess.getHookAccess().getAcceptedArgsAssignment_16(), "rule__Hook__AcceptedArgsAssignment_16");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private EntityDslGrammarAccess grammarAccess;

	@Override
	protected InternalEntityDslParser createParser() {
		InternalEntityDslParser result = new InternalEntityDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public EntityDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EntityDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
