/**
 * generated by Xtext 2.32.0
 */
package co7217.week18.entity.entityDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hook</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co7217.week18.entity.entityDsl.Hook#getHookName <em>Hook Name</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.Hook#getCallbackFunction <em>Callback Function</em>}</li>
 * </ul>
 *
 * @see co7217.week18.entity.entityDsl.EntityDslPackage#getHook()
 * @model
 * @generated
 */
public interface Hook extends EObject
{
  /**
   * Returns the value of the '<em><b>Hook Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hook Name</em>' attribute.
   * @see #setHookName(String)
   * @see co7217.week18.entity.entityDsl.EntityDslPackage#getHook_HookName()
   * @model
   * @generated
   */
  String getHookName();

  /**
   * Sets the value of the '{@link co7217.week18.entity.entityDsl.Hook#getHookName <em>Hook Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hook Name</em>' attribute.
   * @see #getHookName()
   * @generated
   */
  void setHookName(String value);

  /**
   * Returns the value of the '<em><b>Callback Function</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Callback Function</em>' attribute.
   * @see #setCallbackFunction(String)
   * @see co7217.week18.entity.entityDsl.EntityDslPackage#getHook_CallbackFunction()
   * @model
   * @generated
   */
  String getCallbackFunction();

  /**
   * Sets the value of the '{@link co7217.week18.entity.entityDsl.Hook#getCallbackFunction <em>Callback Function</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Callback Function</em>' attribute.
   * @see #getCallbackFunction()
   * @generated
   */
  void setCallbackFunction(String value);

} // Hook
