/**
 * generated by Xtext 2.32.0
 */
package co7217.week18.entity.entityDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Plugin</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co7217.week18.entity.entityDsl.Plugin#getName <em>Name</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.Plugin#getVersion <em>Version</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.Plugin#getDescription <em>Description</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.Plugin#getAuthor <em>Author</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.Plugin#getLicense <em>License</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.Plugin#getPrefix <em>Prefix</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.Plugin#getTextDomain <em>Text Domain</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.Plugin#getActivate <em>Activate</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.Plugin#getDeactivate <em>Deactivate</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.Plugin#getWidgets <em>Widgets</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.Plugin#getShortcodes <em>Shortcodes</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.Plugin#getCustomPostTypes <em>Custom Post Types</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.Plugin#getSettings <em>Settings</em>}</li>
 * </ul>
 *
 * @see co7217.week18.entity.entityDsl.EntityDslPackage#getPlugin()
 * @model
 * @generated
 */
public interface Plugin extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see co7217.week18.entity.entityDsl.EntityDslPackage#getPlugin_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link co7217.week18.entity.entityDsl.Plugin#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Version</em>' attribute.
   * @see #setVersion(String)
   * @see co7217.week18.entity.entityDsl.EntityDslPackage#getPlugin_Version()
   * @model
   * @generated
   */
  String getVersion();

  /**
   * Sets the value of the '{@link co7217.week18.entity.entityDsl.Plugin#getVersion <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Version</em>' attribute.
   * @see #getVersion()
   * @generated
   */
  void setVersion(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see co7217.week18.entity.entityDsl.EntityDslPackage#getPlugin_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link co7217.week18.entity.entityDsl.Plugin#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Author</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Author</em>' attribute.
   * @see #setAuthor(String)
   * @see co7217.week18.entity.entityDsl.EntityDslPackage#getPlugin_Author()
   * @model
   * @generated
   */
  String getAuthor();

  /**
   * Sets the value of the '{@link co7217.week18.entity.entityDsl.Plugin#getAuthor <em>Author</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Author</em>' attribute.
   * @see #getAuthor()
   * @generated
   */
  void setAuthor(String value);

  /**
   * Returns the value of the '<em><b>License</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>License</em>' attribute.
   * @see #setLicense(String)
   * @see co7217.week18.entity.entityDsl.EntityDslPackage#getPlugin_License()
   * @model
   * @generated
   */
  String getLicense();

  /**
   * Sets the value of the '{@link co7217.week18.entity.entityDsl.Plugin#getLicense <em>License</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>License</em>' attribute.
   * @see #getLicense()
   * @generated
   */
  void setLicense(String value);

  /**
   * Returns the value of the '<em><b>Prefix</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prefix</em>' attribute.
   * @see #setPrefix(String)
   * @see co7217.week18.entity.entityDsl.EntityDslPackage#getPlugin_Prefix()
   * @model
   * @generated
   */
  String getPrefix();

  /**
   * Sets the value of the '{@link co7217.week18.entity.entityDsl.Plugin#getPrefix <em>Prefix</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prefix</em>' attribute.
   * @see #getPrefix()
   * @generated
   */
  void setPrefix(String value);

  /**
   * Returns the value of the '<em><b>Text Domain</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text Domain</em>' attribute.
   * @see #setTextDomain(String)
   * @see co7217.week18.entity.entityDsl.EntityDslPackage#getPlugin_TextDomain()
   * @model
   * @generated
   */
  String getTextDomain();

  /**
   * Sets the value of the '{@link co7217.week18.entity.entityDsl.Plugin#getTextDomain <em>Text Domain</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text Domain</em>' attribute.
   * @see #getTextDomain()
   * @generated
   */
  void setTextDomain(String value);

  /**
   * Returns the value of the '<em><b>Activate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Activate</em>' attribute.
   * @see #setActivate(String)
   * @see co7217.week18.entity.entityDsl.EntityDslPackage#getPlugin_Activate()
   * @model
   * @generated
   */
  String getActivate();

  /**
   * Sets the value of the '{@link co7217.week18.entity.entityDsl.Plugin#getActivate <em>Activate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Activate</em>' attribute.
   * @see #getActivate()
   * @generated
   */
  void setActivate(String value);

  /**
   * Returns the value of the '<em><b>Deactivate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Deactivate</em>' attribute.
   * @see #setDeactivate(String)
   * @see co7217.week18.entity.entityDsl.EntityDslPackage#getPlugin_Deactivate()
   * @model
   * @generated
   */
  String getDeactivate();

  /**
   * Sets the value of the '{@link co7217.week18.entity.entityDsl.Plugin#getDeactivate <em>Deactivate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Deactivate</em>' attribute.
   * @see #getDeactivate()
   * @generated
   */
  void setDeactivate(String value);

  /**
   * Returns the value of the '<em><b>Widgets</b></em>' containment reference list.
   * The list contents are of type {@link co7217.week18.entity.entityDsl.Widget}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Widgets</em>' containment reference list.
   * @see co7217.week18.entity.entityDsl.EntityDslPackage#getPlugin_Widgets()
   * @model containment="true"
   * @generated
   */
  EList<Widget> getWidgets();

  /**
   * Returns the value of the '<em><b>Shortcodes</b></em>' containment reference list.
   * The list contents are of type {@link co7217.week18.entity.entityDsl.Shortcode}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Shortcodes</em>' containment reference list.
   * @see co7217.week18.entity.entityDsl.EntityDslPackage#getPlugin_Shortcodes()
   * @model containment="true"
   * @generated
   */
  EList<Shortcode> getShortcodes();

  /**
   * Returns the value of the '<em><b>Custom Post Types</b></em>' containment reference list.
   * The list contents are of type {@link co7217.week18.entity.entityDsl.CustomPostType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Custom Post Types</em>' containment reference list.
   * @see co7217.week18.entity.entityDsl.EntityDslPackage#getPlugin_CustomPostTypes()
   * @model containment="true"
   * @generated
   */
  EList<CustomPostType> getCustomPostTypes();

  /**
   * Returns the value of the '<em><b>Settings</b></em>' containment reference list.
   * The list contents are of type {@link co7217.week18.entity.entityDsl.Setting}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Settings</em>' containment reference list.
   * @see co7217.week18.entity.entityDsl.EntityDslPackage#getPlugin_Settings()
   * @model containment="true"
   * @generated
   */
  EList<Setting> getSettings();

} // Plugin
