/**
 * generated by Xtext 2.32.0
 */
package co7217.week18.entity.entityDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Setting</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co7217.week18.entity.entityDsl.Setting#getSettingName <em>Setting Name</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.Setting#getSettingType <em>Setting Type</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.Setting#getDefaultValue <em>Default Value</em>}</li>
 * </ul>
 *
 * @see co7217.week18.entity.entityDsl.EntityDslPackage#getSetting()
 * @model
 * @generated
 */
public interface Setting extends EObject
{
  /**
   * Returns the value of the '<em><b>Setting Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Setting Name</em>' attribute.
   * @see #setSettingName(String)
   * @see co7217.week18.entity.entityDsl.EntityDslPackage#getSetting_SettingName()
   * @model
   * @generated
   */
  String getSettingName();

  /**
   * Sets the value of the '{@link co7217.week18.entity.entityDsl.Setting#getSettingName <em>Setting Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Setting Name</em>' attribute.
   * @see #getSettingName()
   * @generated
   */
  void setSettingName(String value);

  /**
   * Returns the value of the '<em><b>Setting Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Setting Type</em>' attribute.
   * @see #setSettingType(String)
   * @see co7217.week18.entity.entityDsl.EntityDslPackage#getSetting_SettingType()
   * @model
   * @generated
   */
  String getSettingType();

  /**
   * Sets the value of the '{@link co7217.week18.entity.entityDsl.Setting#getSettingType <em>Setting Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Setting Type</em>' attribute.
   * @see #getSettingType()
   * @generated
   */
  void setSettingType(String value);

  /**
   * Returns the value of the '<em><b>Default Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Default Value</em>' attribute.
   * @see #setDefaultValue(String)
   * @see co7217.week18.entity.entityDsl.EntityDslPackage#getSetting_DefaultValue()
   * @model
   * @generated
   */
  String getDefaultValue();

  /**
   * Sets the value of the '{@link co7217.week18.entity.entityDsl.Setting#getDefaultValue <em>Default Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Default Value</em>' attribute.
   * @see #getDefaultValue()
   * @generated
   */
  void setDefaultValue(String value);

} // Setting
