/**
 * generated by Xtext 2.32.0
 */
package co7217.week18.entity.entityDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Widget</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co7217.week18.entity.entityDsl.Widget#getWidgetName <em>Widget Name</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.Widget#getWidgetDescription <em>Widget Description</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.Widget#getSettings <em>Settings</em>}</li>
 * </ul>
 *
 * @see co7217.week18.entity.entityDsl.EntityDslPackage#getWidget()
 * @model
 * @generated
 */
public interface Widget extends EObject
{
  /**
   * Returns the value of the '<em><b>Widget Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Widget Name</em>' attribute.
   * @see #setWidgetName(String)
   * @see co7217.week18.entity.entityDsl.EntityDslPackage#getWidget_WidgetName()
   * @model
   * @generated
   */
  String getWidgetName();

  /**
   * Sets the value of the '{@link co7217.week18.entity.entityDsl.Widget#getWidgetName <em>Widget Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Widget Name</em>' attribute.
   * @see #getWidgetName()
   * @generated
   */
  void setWidgetName(String value);

  /**
   * Returns the value of the '<em><b>Widget Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Widget Description</em>' attribute.
   * @see #setWidgetDescription(String)
   * @see co7217.week18.entity.entityDsl.EntityDslPackage#getWidget_WidgetDescription()
   * @model
   * @generated
   */
  String getWidgetDescription();

  /**
   * Sets the value of the '{@link co7217.week18.entity.entityDsl.Widget#getWidgetDescription <em>Widget Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Widget Description</em>' attribute.
   * @see #getWidgetDescription()
   * @generated
   */
  void setWidgetDescription(String value);

  /**
   * Returns the value of the '<em><b>Settings</b></em>' containment reference list.
   * The list contents are of type {@link co7217.week18.entity.entityDsl.Setting}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Settings</em>' containment reference list.
   * @see co7217.week18.entity.entityDsl.EntityDslPackage#getWidget_Settings()
   * @model containment="true"
   * @generated
   */
  EList<Setting> getSettings();

} // Widget
