/**
 * generated by Xtext 2.32.0
 */
package co7217.week18.entity.entityDsl.impl;

import co7217.week18.entity.entityDsl.CustomPostType;
import co7217.week18.entity.entityDsl.EntityDslPackage;
import co7217.week18.entity.entityDsl.StringList;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Custom Post Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link co7217.week18.entity.entityDsl.impl.CustomPostTypeImpl#getCptName <em>Cpt Name</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.impl.CustomPostTypeImpl#getCptSingularName <em>Cpt Singular Name</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.impl.CustomPostTypeImpl#getCptSupports <em>Cpt Supports</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.impl.CustomPostTypeImpl#getCptTaxonomies <em>Cpt Taxonomies</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CustomPostTypeImpl extends ElementImpl implements CustomPostType
{
  /**
   * The default value of the '{@link #getCptName() <em>Cpt Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCptName()
   * @generated
   * @ordered
   */
  protected static final String CPT_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCptName() <em>Cpt Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCptName()
   * @generated
   * @ordered
   */
  protected String cptName = CPT_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getCptSingularName() <em>Cpt Singular Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCptSingularName()
   * @generated
   * @ordered
   */
  protected static final String CPT_SINGULAR_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCptSingularName() <em>Cpt Singular Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCptSingularName()
   * @generated
   * @ordered
   */
  protected String cptSingularName = CPT_SINGULAR_NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getCptSupports() <em>Cpt Supports</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCptSupports()
   * @generated
   * @ordered
   */
  protected EList<StringList> cptSupports;

  /**
   * The cached value of the '{@link #getCptTaxonomies() <em>Cpt Taxonomies</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCptTaxonomies()
   * @generated
   * @ordered
   */
  protected EList<StringList> cptTaxonomies;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CustomPostTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EntityDslPackage.Literals.CUSTOM_POST_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCptName()
  {
    return cptName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCptName(String newCptName)
  {
    String oldCptName = cptName;
    cptName = newCptName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntityDslPackage.CUSTOM_POST_TYPE__CPT_NAME, oldCptName, cptName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCptSingularName()
  {
    return cptSingularName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCptSingularName(String newCptSingularName)
  {
    String oldCptSingularName = cptSingularName;
    cptSingularName = newCptSingularName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntityDslPackage.CUSTOM_POST_TYPE__CPT_SINGULAR_NAME, oldCptSingularName, cptSingularName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<StringList> getCptSupports()
  {
    if (cptSupports == null)
    {
      cptSupports = new EObjectContainmentEList<StringList>(StringList.class, this, EntityDslPackage.CUSTOM_POST_TYPE__CPT_SUPPORTS);
    }
    return cptSupports;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<StringList> getCptTaxonomies()
  {
    if (cptTaxonomies == null)
    {
      cptTaxonomies = new EObjectContainmentEList<StringList>(StringList.class, this, EntityDslPackage.CUSTOM_POST_TYPE__CPT_TAXONOMIES);
    }
    return cptTaxonomies;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EntityDslPackage.CUSTOM_POST_TYPE__CPT_SUPPORTS:
        return ((InternalEList<?>)getCptSupports()).basicRemove(otherEnd, msgs);
      case EntityDslPackage.CUSTOM_POST_TYPE__CPT_TAXONOMIES:
        return ((InternalEList<?>)getCptTaxonomies()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EntityDslPackage.CUSTOM_POST_TYPE__CPT_NAME:
        return getCptName();
      case EntityDslPackage.CUSTOM_POST_TYPE__CPT_SINGULAR_NAME:
        return getCptSingularName();
      case EntityDslPackage.CUSTOM_POST_TYPE__CPT_SUPPORTS:
        return getCptSupports();
      case EntityDslPackage.CUSTOM_POST_TYPE__CPT_TAXONOMIES:
        return getCptTaxonomies();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EntityDslPackage.CUSTOM_POST_TYPE__CPT_NAME:
        setCptName((String)newValue);
        return;
      case EntityDslPackage.CUSTOM_POST_TYPE__CPT_SINGULAR_NAME:
        setCptSingularName((String)newValue);
        return;
      case EntityDslPackage.CUSTOM_POST_TYPE__CPT_SUPPORTS:
        getCptSupports().clear();
        getCptSupports().addAll((Collection<? extends StringList>)newValue);
        return;
      case EntityDslPackage.CUSTOM_POST_TYPE__CPT_TAXONOMIES:
        getCptTaxonomies().clear();
        getCptTaxonomies().addAll((Collection<? extends StringList>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EntityDslPackage.CUSTOM_POST_TYPE__CPT_NAME:
        setCptName(CPT_NAME_EDEFAULT);
        return;
      case EntityDslPackage.CUSTOM_POST_TYPE__CPT_SINGULAR_NAME:
        setCptSingularName(CPT_SINGULAR_NAME_EDEFAULT);
        return;
      case EntityDslPackage.CUSTOM_POST_TYPE__CPT_SUPPORTS:
        getCptSupports().clear();
        return;
      case EntityDslPackage.CUSTOM_POST_TYPE__CPT_TAXONOMIES:
        getCptTaxonomies().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EntityDslPackage.CUSTOM_POST_TYPE__CPT_NAME:
        return CPT_NAME_EDEFAULT == null ? cptName != null : !CPT_NAME_EDEFAULT.equals(cptName);
      case EntityDslPackage.CUSTOM_POST_TYPE__CPT_SINGULAR_NAME:
        return CPT_SINGULAR_NAME_EDEFAULT == null ? cptSingularName != null : !CPT_SINGULAR_NAME_EDEFAULT.equals(cptSingularName);
      case EntityDslPackage.CUSTOM_POST_TYPE__CPT_SUPPORTS:
        return cptSupports != null && !cptSupports.isEmpty();
      case EntityDslPackage.CUSTOM_POST_TYPE__CPT_TAXONOMIES:
        return cptTaxonomies != null && !cptTaxonomies.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (cptName: ");
    result.append(cptName);
    result.append(", cptSingularName: ");
    result.append(cptSingularName);
    result.append(')');
    return result.toString();
  }

} //CustomPostTypeImpl
