/**
 * generated by Xtext 2.32.0
 */
package co7217.week18.entity.entityDsl.impl;

import co7217.week18.entity.entityDsl.CustomPostType;
import co7217.week18.entity.entityDsl.EntityDslPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Custom Post Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link co7217.week18.entity.entityDsl.impl.CustomPostTypeImpl#getPostTypeName <em>Post Type Name</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.impl.CustomPostTypeImpl#getSupports <em>Supports</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.impl.CustomPostTypeImpl#getTaxonomies <em>Taxonomies</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CustomPostTypeImpl extends MinimalEObjectImpl.Container implements CustomPostType
{
  /**
   * The default value of the '{@link #getPostTypeName() <em>Post Type Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPostTypeName()
   * @generated
   * @ordered
   */
  protected static final String POST_TYPE_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPostTypeName() <em>Post Type Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPostTypeName()
   * @generated
   * @ordered
   */
  protected String postTypeName = POST_TYPE_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getSupports() <em>Supports</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSupports()
   * @generated
   * @ordered
   */
  protected static final String SUPPORTS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSupports() <em>Supports</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSupports()
   * @generated
   * @ordered
   */
  protected String supports = SUPPORTS_EDEFAULT;

  /**
   * The default value of the '{@link #getTaxonomies() <em>Taxonomies</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTaxonomies()
   * @generated
   * @ordered
   */
  protected static final String TAXONOMIES_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTaxonomies() <em>Taxonomies</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTaxonomies()
   * @generated
   * @ordered
   */
  protected String taxonomies = TAXONOMIES_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CustomPostTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EntityDslPackage.Literals.CUSTOM_POST_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPostTypeName()
  {
    return postTypeName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPostTypeName(String newPostTypeName)
  {
    String oldPostTypeName = postTypeName;
    postTypeName = newPostTypeName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntityDslPackage.CUSTOM_POST_TYPE__POST_TYPE_NAME, oldPostTypeName, postTypeName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSupports()
  {
    return supports;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSupports(String newSupports)
  {
    String oldSupports = supports;
    supports = newSupports;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntityDslPackage.CUSTOM_POST_TYPE__SUPPORTS, oldSupports, supports));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTaxonomies()
  {
    return taxonomies;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTaxonomies(String newTaxonomies)
  {
    String oldTaxonomies = taxonomies;
    taxonomies = newTaxonomies;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntityDslPackage.CUSTOM_POST_TYPE__TAXONOMIES, oldTaxonomies, taxonomies));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EntityDslPackage.CUSTOM_POST_TYPE__POST_TYPE_NAME:
        return getPostTypeName();
      case EntityDslPackage.CUSTOM_POST_TYPE__SUPPORTS:
        return getSupports();
      case EntityDslPackage.CUSTOM_POST_TYPE__TAXONOMIES:
        return getTaxonomies();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EntityDslPackage.CUSTOM_POST_TYPE__POST_TYPE_NAME:
        setPostTypeName((String)newValue);
        return;
      case EntityDslPackage.CUSTOM_POST_TYPE__SUPPORTS:
        setSupports((String)newValue);
        return;
      case EntityDslPackage.CUSTOM_POST_TYPE__TAXONOMIES:
        setTaxonomies((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EntityDslPackage.CUSTOM_POST_TYPE__POST_TYPE_NAME:
        setPostTypeName(POST_TYPE_NAME_EDEFAULT);
        return;
      case EntityDslPackage.CUSTOM_POST_TYPE__SUPPORTS:
        setSupports(SUPPORTS_EDEFAULT);
        return;
      case EntityDslPackage.CUSTOM_POST_TYPE__TAXONOMIES:
        setTaxonomies(TAXONOMIES_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EntityDslPackage.CUSTOM_POST_TYPE__POST_TYPE_NAME:
        return POST_TYPE_NAME_EDEFAULT == null ? postTypeName != null : !POST_TYPE_NAME_EDEFAULT.equals(postTypeName);
      case EntityDslPackage.CUSTOM_POST_TYPE__SUPPORTS:
        return SUPPORTS_EDEFAULT == null ? supports != null : !SUPPORTS_EDEFAULT.equals(supports);
      case EntityDslPackage.CUSTOM_POST_TYPE__TAXONOMIES:
        return TAXONOMIES_EDEFAULT == null ? taxonomies != null : !TAXONOMIES_EDEFAULT.equals(taxonomies);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (postTypeName: ");
    result.append(postTypeName);
    result.append(", supports: ");
    result.append(supports);
    result.append(", taxonomies: ");
    result.append(taxonomies);
    result.append(')');
    return result.toString();
  }

} //CustomPostTypeImpl
