/**
 * generated by Xtext 2.32.0
 */
package co7217.week18.entity.entityDsl.impl;

import co7217.week18.entity.entityDsl.EntityDslPackage;
import co7217.week18.entity.entityDsl.Hook;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Hook</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link co7217.week18.entity.entityDsl.impl.HookImpl#getHookName <em>Hook Name</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.impl.HookImpl#getCallbackFunction <em>Callback Function</em>}</li>
 * </ul>
 *
 * @generated
 */
public class HookImpl extends MinimalEObjectImpl.Container implements Hook
{
  /**
   * The default value of the '{@link #getHookName() <em>Hook Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHookName()
   * @generated
   * @ordered
   */
  protected static final String HOOK_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getHookName() <em>Hook Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHookName()
   * @generated
   * @ordered
   */
  protected String hookName = HOOK_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getCallbackFunction() <em>Callback Function</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCallbackFunction()
   * @generated
   * @ordered
   */
  protected static final String CALLBACK_FUNCTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCallbackFunction() <em>Callback Function</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCallbackFunction()
   * @generated
   * @ordered
   */
  protected String callbackFunction = CALLBACK_FUNCTION_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected HookImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EntityDslPackage.Literals.HOOK;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getHookName()
  {
    return hookName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHookName(String newHookName)
  {
    String oldHookName = hookName;
    hookName = newHookName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntityDslPackage.HOOK__HOOK_NAME, oldHookName, hookName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCallbackFunction()
  {
    return callbackFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCallbackFunction(String newCallbackFunction)
  {
    String oldCallbackFunction = callbackFunction;
    callbackFunction = newCallbackFunction;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntityDslPackage.HOOK__CALLBACK_FUNCTION, oldCallbackFunction, callbackFunction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EntityDslPackage.HOOK__HOOK_NAME:
        return getHookName();
      case EntityDslPackage.HOOK__CALLBACK_FUNCTION:
        return getCallbackFunction();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EntityDslPackage.HOOK__HOOK_NAME:
        setHookName((String)newValue);
        return;
      case EntityDslPackage.HOOK__CALLBACK_FUNCTION:
        setCallbackFunction((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EntityDslPackage.HOOK__HOOK_NAME:
        setHookName(HOOK_NAME_EDEFAULT);
        return;
      case EntityDslPackage.HOOK__CALLBACK_FUNCTION:
        setCallbackFunction(CALLBACK_FUNCTION_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EntityDslPackage.HOOK__HOOK_NAME:
        return HOOK_NAME_EDEFAULT == null ? hookName != null : !HOOK_NAME_EDEFAULT.equals(hookName);
      case EntityDslPackage.HOOK__CALLBACK_FUNCTION:
        return CALLBACK_FUNCTION_EDEFAULT == null ? callbackFunction != null : !CALLBACK_FUNCTION_EDEFAULT.equals(callbackFunction);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (hookName: ");
    result.append(hookName);
    result.append(", callbackFunction: ");
    result.append(callbackFunction);
    result.append(')');
    return result.toString();
  }

} //HookImpl
