/**
 * generated by Xtext 2.32.0
 */
package co7217.week18.entity.entityDsl.impl;

import co7217.week18.entity.entityDsl.EntityDslPackage;
import co7217.week18.entity.entityDsl.Meta;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Meta</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link co7217.week18.entity.entityDsl.impl.MetaImpl#getName <em>Name</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.impl.MetaImpl#getVersion <em>Version</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.impl.MetaImpl#getDescription <em>Description</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.impl.MetaImpl#getAuthor <em>Author</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.impl.MetaImpl#getLicense <em>License</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.impl.MetaImpl#getPrefix <em>Prefix</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.impl.MetaImpl#getTextDomain <em>Text Domain</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.impl.MetaImpl#getActivate <em>Activate</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.impl.MetaImpl#getDeactivate <em>Deactivate</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.impl.MetaImpl#getUninstall <em>Uninstall</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MetaImpl extends ElementImpl implements Meta
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getVersion() <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVersion()
   * @generated
   * @ordered
   */
  protected static final String VERSION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVersion() <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVersion()
   * @generated
   * @ordered
   */
  protected String version = VERSION_EDEFAULT;

  /**
   * The default value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected static final String DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected String description = DESCRIPTION_EDEFAULT;

  /**
   * The default value of the '{@link #getAuthor() <em>Author</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAuthor()
   * @generated
   * @ordered
   */
  protected static final String AUTHOR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAuthor() <em>Author</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAuthor()
   * @generated
   * @ordered
   */
  protected String author = AUTHOR_EDEFAULT;

  /**
   * The default value of the '{@link #getLicense() <em>License</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLicense()
   * @generated
   * @ordered
   */
  protected static final String LICENSE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLicense() <em>License</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLicense()
   * @generated
   * @ordered
   */
  protected String license = LICENSE_EDEFAULT;

  /**
   * The default value of the '{@link #getPrefix() <em>Prefix</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrefix()
   * @generated
   * @ordered
   */
  protected static final String PREFIX_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPrefix() <em>Prefix</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrefix()
   * @generated
   * @ordered
   */
  protected String prefix = PREFIX_EDEFAULT;

  /**
   * The default value of the '{@link #getTextDomain() <em>Text Domain</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTextDomain()
   * @generated
   * @ordered
   */
  protected static final String TEXT_DOMAIN_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTextDomain() <em>Text Domain</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTextDomain()
   * @generated
   * @ordered
   */
  protected String textDomain = TEXT_DOMAIN_EDEFAULT;

  /**
   * The default value of the '{@link #getActivate() <em>Activate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getActivate()
   * @generated
   * @ordered
   */
  protected static final String ACTIVATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getActivate() <em>Activate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getActivate()
   * @generated
   * @ordered
   */
  protected String activate = ACTIVATE_EDEFAULT;

  /**
   * The default value of the '{@link #getDeactivate() <em>Deactivate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeactivate()
   * @generated
   * @ordered
   */
  protected static final String DEACTIVATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDeactivate() <em>Deactivate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeactivate()
   * @generated
   * @ordered
   */
  protected String deactivate = DEACTIVATE_EDEFAULT;

  /**
   * The default value of the '{@link #getUninstall() <em>Uninstall</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUninstall()
   * @generated
   * @ordered
   */
  protected static final String UNINSTALL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getUninstall() <em>Uninstall</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUninstall()
   * @generated
   * @ordered
   */
  protected String uninstall = UNINSTALL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MetaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EntityDslPackage.Literals.META;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntityDslPackage.META__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVersion()
  {
    return version;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVersion(String newVersion)
  {
    String oldVersion = version;
    version = newVersion;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntityDslPackage.META__VERSION, oldVersion, version));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDescription()
  {
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDescription(String newDescription)
  {
    String oldDescription = description;
    description = newDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntityDslPackage.META__DESCRIPTION, oldDescription, description));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAuthor()
  {
    return author;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAuthor(String newAuthor)
  {
    String oldAuthor = author;
    author = newAuthor;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntityDslPackage.META__AUTHOR, oldAuthor, author));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLicense()
  {
    return license;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLicense(String newLicense)
  {
    String oldLicense = license;
    license = newLicense;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntityDslPackage.META__LICENSE, oldLicense, license));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPrefix()
  {
    return prefix;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPrefix(String newPrefix)
  {
    String oldPrefix = prefix;
    prefix = newPrefix;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntityDslPackage.META__PREFIX, oldPrefix, prefix));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTextDomain()
  {
    return textDomain;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTextDomain(String newTextDomain)
  {
    String oldTextDomain = textDomain;
    textDomain = newTextDomain;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntityDslPackage.META__TEXT_DOMAIN, oldTextDomain, textDomain));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getActivate()
  {
    return activate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setActivate(String newActivate)
  {
    String oldActivate = activate;
    activate = newActivate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntityDslPackage.META__ACTIVATE, oldActivate, activate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDeactivate()
  {
    return deactivate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDeactivate(String newDeactivate)
  {
    String oldDeactivate = deactivate;
    deactivate = newDeactivate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntityDslPackage.META__DEACTIVATE, oldDeactivate, deactivate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getUninstall()
  {
    return uninstall;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUninstall(String newUninstall)
  {
    String oldUninstall = uninstall;
    uninstall = newUninstall;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntityDslPackage.META__UNINSTALL, oldUninstall, uninstall));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EntityDslPackage.META__NAME:
        return getName();
      case EntityDslPackage.META__VERSION:
        return getVersion();
      case EntityDslPackage.META__DESCRIPTION:
        return getDescription();
      case EntityDslPackage.META__AUTHOR:
        return getAuthor();
      case EntityDslPackage.META__LICENSE:
        return getLicense();
      case EntityDslPackage.META__PREFIX:
        return getPrefix();
      case EntityDslPackage.META__TEXT_DOMAIN:
        return getTextDomain();
      case EntityDslPackage.META__ACTIVATE:
        return getActivate();
      case EntityDslPackage.META__DEACTIVATE:
        return getDeactivate();
      case EntityDslPackage.META__UNINSTALL:
        return getUninstall();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EntityDslPackage.META__NAME:
        setName((String)newValue);
        return;
      case EntityDslPackage.META__VERSION:
        setVersion((String)newValue);
        return;
      case EntityDslPackage.META__DESCRIPTION:
        setDescription((String)newValue);
        return;
      case EntityDslPackage.META__AUTHOR:
        setAuthor((String)newValue);
        return;
      case EntityDslPackage.META__LICENSE:
        setLicense((String)newValue);
        return;
      case EntityDslPackage.META__PREFIX:
        setPrefix((String)newValue);
        return;
      case EntityDslPackage.META__TEXT_DOMAIN:
        setTextDomain((String)newValue);
        return;
      case EntityDslPackage.META__ACTIVATE:
        setActivate((String)newValue);
        return;
      case EntityDslPackage.META__DEACTIVATE:
        setDeactivate((String)newValue);
        return;
      case EntityDslPackage.META__UNINSTALL:
        setUninstall((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EntityDslPackage.META__NAME:
        setName(NAME_EDEFAULT);
        return;
      case EntityDslPackage.META__VERSION:
        setVersion(VERSION_EDEFAULT);
        return;
      case EntityDslPackage.META__DESCRIPTION:
        setDescription(DESCRIPTION_EDEFAULT);
        return;
      case EntityDslPackage.META__AUTHOR:
        setAuthor(AUTHOR_EDEFAULT);
        return;
      case EntityDslPackage.META__LICENSE:
        setLicense(LICENSE_EDEFAULT);
        return;
      case EntityDslPackage.META__PREFIX:
        setPrefix(PREFIX_EDEFAULT);
        return;
      case EntityDslPackage.META__TEXT_DOMAIN:
        setTextDomain(TEXT_DOMAIN_EDEFAULT);
        return;
      case EntityDslPackage.META__ACTIVATE:
        setActivate(ACTIVATE_EDEFAULT);
        return;
      case EntityDslPackage.META__DEACTIVATE:
        setDeactivate(DEACTIVATE_EDEFAULT);
        return;
      case EntityDslPackage.META__UNINSTALL:
        setUninstall(UNINSTALL_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EntityDslPackage.META__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case EntityDslPackage.META__VERSION:
        return VERSION_EDEFAULT == null ? version != null : !VERSION_EDEFAULT.equals(version);
      case EntityDslPackage.META__DESCRIPTION:
        return DESCRIPTION_EDEFAULT == null ? description != null : !DESCRIPTION_EDEFAULT.equals(description);
      case EntityDslPackage.META__AUTHOR:
        return AUTHOR_EDEFAULT == null ? author != null : !AUTHOR_EDEFAULT.equals(author);
      case EntityDslPackage.META__LICENSE:
        return LICENSE_EDEFAULT == null ? license != null : !LICENSE_EDEFAULT.equals(license);
      case EntityDslPackage.META__PREFIX:
        return PREFIX_EDEFAULT == null ? prefix != null : !PREFIX_EDEFAULT.equals(prefix);
      case EntityDslPackage.META__TEXT_DOMAIN:
        return TEXT_DOMAIN_EDEFAULT == null ? textDomain != null : !TEXT_DOMAIN_EDEFAULT.equals(textDomain);
      case EntityDslPackage.META__ACTIVATE:
        return ACTIVATE_EDEFAULT == null ? activate != null : !ACTIVATE_EDEFAULT.equals(activate);
      case EntityDslPackage.META__DEACTIVATE:
        return DEACTIVATE_EDEFAULT == null ? deactivate != null : !DEACTIVATE_EDEFAULT.equals(deactivate);
      case EntityDslPackage.META__UNINSTALL:
        return UNINSTALL_EDEFAULT == null ? uninstall != null : !UNINSTALL_EDEFAULT.equals(uninstall);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", version: ");
    result.append(version);
    result.append(", description: ");
    result.append(description);
    result.append(", author: ");
    result.append(author);
    result.append(", license: ");
    result.append(license);
    result.append(", prefix: ");
    result.append(prefix);
    result.append(", textDomain: ");
    result.append(textDomain);
    result.append(", activate: ");
    result.append(activate);
    result.append(", deactivate: ");
    result.append(deactivate);
    result.append(", uninstall: ");
    result.append(uninstall);
    result.append(')');
    return result.toString();
  }

} //MetaImpl
