/**
 * generated by Xtext 2.32.0
 */
package co7217.week18.entity.entityDsl.impl;

import co7217.week18.entity.entityDsl.EntityDslPackage;
import co7217.week18.entity.entityDsl.Setting;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Setting</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link co7217.week18.entity.entityDsl.impl.SettingImpl#getSettingName <em>Setting Name</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.impl.SettingImpl#getSettingType <em>Setting Type</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.impl.SettingImpl#getDefaultValue <em>Default Value</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SettingImpl extends ElementImpl implements Setting
{
  /**
   * The default value of the '{@link #getSettingName() <em>Setting Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSettingName()
   * @generated
   * @ordered
   */
  protected static final String SETTING_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSettingName() <em>Setting Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSettingName()
   * @generated
   * @ordered
   */
  protected String settingName = SETTING_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getSettingType() <em>Setting Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSettingType()
   * @generated
   * @ordered
   */
  protected static final String SETTING_TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSettingType() <em>Setting Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSettingType()
   * @generated
   * @ordered
   */
  protected String settingType = SETTING_TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getDefaultValue() <em>Default Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefaultValue()
   * @generated
   * @ordered
   */
  protected static final String DEFAULT_VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDefaultValue() <em>Default Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefaultValue()
   * @generated
   * @ordered
   */
  protected String defaultValue = DEFAULT_VALUE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SettingImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EntityDslPackage.Literals.SETTING;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSettingName()
  {
    return settingName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSettingName(String newSettingName)
  {
    String oldSettingName = settingName;
    settingName = newSettingName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntityDslPackage.SETTING__SETTING_NAME, oldSettingName, settingName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSettingType()
  {
    return settingType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSettingType(String newSettingType)
  {
    String oldSettingType = settingType;
    settingType = newSettingType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntityDslPackage.SETTING__SETTING_TYPE, oldSettingType, settingType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDefaultValue()
  {
    return defaultValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDefaultValue(String newDefaultValue)
  {
    String oldDefaultValue = defaultValue;
    defaultValue = newDefaultValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntityDslPackage.SETTING__DEFAULT_VALUE, oldDefaultValue, defaultValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EntityDslPackage.SETTING__SETTING_NAME:
        return getSettingName();
      case EntityDslPackage.SETTING__SETTING_TYPE:
        return getSettingType();
      case EntityDslPackage.SETTING__DEFAULT_VALUE:
        return getDefaultValue();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EntityDslPackage.SETTING__SETTING_NAME:
        setSettingName((String)newValue);
        return;
      case EntityDslPackage.SETTING__SETTING_TYPE:
        setSettingType((String)newValue);
        return;
      case EntityDslPackage.SETTING__DEFAULT_VALUE:
        setDefaultValue((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EntityDslPackage.SETTING__SETTING_NAME:
        setSettingName(SETTING_NAME_EDEFAULT);
        return;
      case EntityDslPackage.SETTING__SETTING_TYPE:
        setSettingType(SETTING_TYPE_EDEFAULT);
        return;
      case EntityDslPackage.SETTING__DEFAULT_VALUE:
        setDefaultValue(DEFAULT_VALUE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EntityDslPackage.SETTING__SETTING_NAME:
        return SETTING_NAME_EDEFAULT == null ? settingName != null : !SETTING_NAME_EDEFAULT.equals(settingName);
      case EntityDslPackage.SETTING__SETTING_TYPE:
        return SETTING_TYPE_EDEFAULT == null ? settingType != null : !SETTING_TYPE_EDEFAULT.equals(settingType);
      case EntityDslPackage.SETTING__DEFAULT_VALUE:
        return DEFAULT_VALUE_EDEFAULT == null ? defaultValue != null : !DEFAULT_VALUE_EDEFAULT.equals(defaultValue);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (settingName: ");
    result.append(settingName);
    result.append(", settingType: ");
    result.append(settingType);
    result.append(", defaultValue: ");
    result.append(defaultValue);
    result.append(')');
    return result.toString();
  }

} //SettingImpl
