/**
 * generated by Xtext 2.32.0
 */
package co7217.week18.entity.entityDsl.impl;

import co7217.week18.entity.entityDsl.EntityDslPackage;
import co7217.week18.entity.entityDsl.Hook;
import co7217.week18.entity.entityDsl.Shortcode;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Shortcode</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link co7217.week18.entity.entityDsl.impl.ShortcodeImpl#getShortcodeName <em>Shortcode Name</em>}</li>
 *   <li>{@link co7217.week18.entity.entityDsl.impl.ShortcodeImpl#getHooks <em>Hooks</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ShortcodeImpl extends MinimalEObjectImpl.Container implements Shortcode
{
  /**
   * The default value of the '{@link #getShortcodeName() <em>Shortcode Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShortcodeName()
   * @generated
   * @ordered
   */
  protected static final String SHORTCODE_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getShortcodeName() <em>Shortcode Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShortcodeName()
   * @generated
   * @ordered
   */
  protected String shortcodeName = SHORTCODE_NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getHooks() <em>Hooks</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHooks()
   * @generated
   * @ordered
   */
  protected EList<Hook> hooks;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ShortcodeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EntityDslPackage.Literals.SHORTCODE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getShortcodeName()
  {
    return shortcodeName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setShortcodeName(String newShortcodeName)
  {
    String oldShortcodeName = shortcodeName;
    shortcodeName = newShortcodeName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntityDslPackage.SHORTCODE__SHORTCODE_NAME, oldShortcodeName, shortcodeName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Hook> getHooks()
  {
    if (hooks == null)
    {
      hooks = new EObjectContainmentEList<Hook>(Hook.class, this, EntityDslPackage.SHORTCODE__HOOKS);
    }
    return hooks;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EntityDslPackage.SHORTCODE__HOOKS:
        return ((InternalEList<?>)getHooks()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EntityDslPackage.SHORTCODE__SHORTCODE_NAME:
        return getShortcodeName();
      case EntityDslPackage.SHORTCODE__HOOKS:
        return getHooks();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EntityDslPackage.SHORTCODE__SHORTCODE_NAME:
        setShortcodeName((String)newValue);
        return;
      case EntityDslPackage.SHORTCODE__HOOKS:
        getHooks().clear();
        getHooks().addAll((Collection<? extends Hook>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EntityDslPackage.SHORTCODE__SHORTCODE_NAME:
        setShortcodeName(SHORTCODE_NAME_EDEFAULT);
        return;
      case EntityDslPackage.SHORTCODE__HOOKS:
        getHooks().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EntityDslPackage.SHORTCODE__SHORTCODE_NAME:
        return SHORTCODE_NAME_EDEFAULT == null ? shortcodeName != null : !SHORTCODE_NAME_EDEFAULT.equals(shortcodeName);
      case EntityDslPackage.SHORTCODE__HOOKS:
        return hooks != null && !hooks.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (shortcodeName: ");
    result.append(shortcodeName);
    result.append(')');
    return result.toString();
  }

} //ShortcodeImpl
